(source gnu)
(source melpa)

(depends-on "cider")
(depends-on "cask")
(depends-on "base15-emacs" :git "http://github.com/neil477/base16-emacs.git")
(depends-on "dash")
(depends-on "anzu")
(depends-on "httprepl")
(depends-on "swoop")
(depends-on "highlight-cl")
(depends-on "column-enforce-mode")
(depends-on "exec-path-from-shell")
(depends-on "slamhound")
(depends-on "company")
(depends-on "s")
(depends-on "dired+")
(depends-on "erc-terminal-notifier")
(depends-on "evil")
(depends-on "evil-surround")
(depends-on "evil-indent-textobject")
(depends-on "ace-jump-mode")
(depends-on "expand-region")
(depends-on "flycheck")
(depends-on "magit")
(depends-on "yagist")
(depends-on "diff-hl")
(depends-on "gh")
(depends-on "git-timemachine")
(depends-on "magit-gh-pulls")
(depends-on "open-github-from-here" :git "http://github.com/mbriggs/emacs-open-github-from-here.git")
(depends-on "discover-my-major" :git "http://github.com/steckerhalter/discover-my-major.git")
(depends-on "magit-gh-pulls")
(depends-on "ido-vertical-mode")
(depends-on "ido-ubiquitous")
(depends-on "smex")
(depends-on "ido-hacks")
(depends-on "flx-ido")
(depends-on "emacs-eclim")
(depends-on "go-mode" :git "http://github.com/dominikh/go-mode.el.git")
(depends-on "js2-mode")
(depends-on "coffee-mode")
(depends-on "js2-jshint" :git "http://github.com/michaeljb/js2-jshint.git")
(depends-on "gulpjs" :git "http://github.com/stevenremot/emacs-gulpjs.git")
(depends-on "inf-mongo" :git "http://github.com/tobiassvn/inf-mongo.git")
(depends-on "multiple-cursors")
(depends-on "markdown-mode")
(depends-on "projectile")
(depends-on "prodigy")
(depends-on "rbenv")
(depends-on "bundler")
(depends-on "rspec-mode")
(depends-on "ruby-refactor")
(depends-on "rails-log-mode")
(depends-on "rubocop")
(depends-on "inf-ruby")
(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "yasnippet")
(depends-on "auto-yasnippet")
(depends-on "multi-term")
(depends-on "session")
(depends-on "volatile-highlights")
(depends-on "web-mode")
(depends-on "emmet-mode")
(depends-on "yaml-mode")
(depends-on "smartparens" :git "http://github.com/Fuco1/smartparens.git")
